# Generated by Django 6.0.7 on 2026-07-11 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=40, unique=True)),
                ('outlet_name', models.CharField(max_length=150)),
                ('physical_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('safety_cash_threshold', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.area')),
            ],
        ),
        migrations.CreateModel(
            name='AgentProviderBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('safety_threshold', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('data_timestamp', models.DateTimeField()),
                ('data_status', models.CharField(choices=[('FRESH', 'Fresh'), ('DELAYED', 'Delayed'), ('MISSING', 'Missing'), ('CONFLICTING', 'Conflicting')], default='FRESH', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_balances', to='agents.agent')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.provider')),
            ],
            options={
                'unique_together': {('agent', 'provider')},
            },
        ),
    ]
