# Generated by Django 5.2.6 on 2026-07-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentproviderbalance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='agentproviderbalance',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_balances', to='agents.provider'),
        ),
        migrations.AddConstraint(
            model_name='agentproviderbalance',
            constraint=models.UniqueConstraint(fields=('agent', 'provider'), name='unique_agent_provider_balance'),
        ),
    ]
