# Generated by Django 6.0.7 on 2026-07-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('FORECAST_MAE', 'Forecast MAE'), ('SHORTAGE_LEAD_TIME', 'Shortage Lead Time'), ('ANOMALY_PRECISION', 'Anomaly Precision'), ('ANOMALY_RECALL', 'Anomaly Recall'), ('FALSE_POSITIVE_RATE', 'False Positive Rate'), ('EXPLANATION_COVERAGE', 'Explanation Coverage'), ('API_LATENCY', 'API Latency'), ('ALERT_OWNERSHIP', 'Alert Ownership')], max_length=40)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiquidityForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('PROVIDER_BALANCE', 'Provider Balance'), ('PHYSICAL_CASH', 'Physical Cash')], default='PROVIDER_BALANCE', max_length=30)),
                ('forecast_hours', models.PositiveIntegerField(default=2)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('predicted_demand', models.DecimalField(decimal_places=2, max_digits=14)),
                ('projected_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('safety_threshold', models.DecimalField(decimal_places=2, max_digits=14)),
                ('shortage_probability', models.FloatField(default=0, help_text='Store probability as a value between 0 and 100.')),
                ('confidence', models.FloatField(default=0, help_text='Store confidence as a value between 0 and 100.')),
                ('estimated_shortage_at', models.DateTimeField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='agents.agent')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='agents.provider')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
