# Generated by Django 6.0.7 on 2026-07-11 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('AGENT', 'Agent'), ('FIELD_OFFICER', 'Field Officer'), ('OPERATIONS', 'Operations'), ('RISK_REVIEWER', 'Risk Reviewer')], default='AGENT', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('preferred_language', models.CharField(choices=[('EN', 'English'), ('BN', 'Bengali')], default='EN', max_length=5)),
                ('receive_critical_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_profiles', to='agents.area')),
                ('assigned_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_profiles', to='agents.provider')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
